backend:
  name: git-gateway
  branch: master   # 請依你的 repo 實際分支（main 或 master）

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

locale: "zh_Hant"         # 後台語系為繁體

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime" }
      - { label: "精選圖片", name: "featured_image", widget: "image", required: false }
      - { label: "描述", name: "description", widget: "string", required: false }
      - { label: "分類", name: "categories", widget: "list", required: false }
      - { label: "標籤", name: "tags", widget: "list", required: false }
      - { label: "正文內容", name: "body", widget: "markdown" }
  - name: "pages"
    label: "單頁"
    folder: "content"
    create: true
    slug: "{{slug}}"
    filter: { field: "type", value: "page" }
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime", required: false }
      - { label: "精選圖片", name: "featured_image", widget: "image", required: false }
      - { label: "正文內容", name: "body", widget: "markdown" }
  - name: "categories"
    label: "分類"
    folder: "content/categories"
    create: true
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "說明", name: "description", widget: "string", required: false }
  - name: "tags"
    label: "標籤"
    folder: "content/tags"
    create: true
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "說明", name: "description", widget: "string", required: false }
  - name: "homepage"
    label: "首頁設定"
    files:
      - label: "首頁視覺設定"
        name: "home"
        file: "content/_index.md"     # 或 "data/homepage.yaml"
        fields:
          - { label: "首頁標題", name: "title", widget: "string" }
          - { label: "副標題", name: "subtitle", widget: "string", required: false }
          - { label: "Banner 圖片", name: "banner", widget: "image" }
          - { label: "Logo", name: "logo", widget: "image" }
