backend:
  name: git-gateway
  branch: master   # 若用 main 請改此處

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "Banner", name: "banner", widget: "image" }
      - { label: "內容", name: "body", widget: "markdown" }

