backend:
  name: git-gateway
  branch: master         # 可依你的 deploy 分支調整

media_folder: "static/images/uploads"     # 圖片上傳路徑
public_folder: "/images/uploads"

site_url: "https://your-crypto-news.netlify.app/"   # 網站網址
locale: "zh_cht"         # 後台語系為繁體

collections:
  - name: 'posts'
    label: '文章'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '標題', name: 'title', widget: 'string' }
      - { label: '發布日期', name: 'date', widget: 'datetime' }
      - { label: '內容', name: 'body', widget: 'markdown' }
      - { label: '作者', name: 'author', widget: 'string' }
      - { label: '短網址', name: 'slug', widget: 'string' }
      - { label: "標籤", name: "tags", widget: "list", required: false}
      - { label: "分類", name: "categories", widget: "list", required: false}
  - name: "categories"
    label: "分類"
    folder: "content/categories"
    create: true
    fields:
      - {label: "標題", name: "title", widget: "string"}
      - {label: "內容", name: "body", widget: "markdown", required: false}
  - name: "tags"
    label: "標籤"
    folder: "content/tags"
    create: true
    fields:
      - {label: "標題", name: "title", widget: "string"}
      - {label: "內容", name: "body", widget: "markdown", required: false}
