name: Sync Hugo Content from S3

on:
  schedule:
    - cron: '*/5 * * * *'   # 每 5 分鐘執行一次
  workflow_dispatch:        # 亦可手動觸發

permissions:
  id-token: write
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::324183266130:role/github-actions-oidc-role"
          aws-region: ap-southeast-2

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current working directory
        run: |
          echo "PWD with shell: $PWD"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "::notice file=workflow::$PWD"
          ls -al

      - name: Set git user
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Sync content from S3
        run: |
          aws s3 sync s3://sd-images-20250701-columnbb15/posts/ content/posts/
          aws s3 sync s3://sd-images-20250701-columnbb15/images/ static/images/

      - name: Commit & Push changes
        run: |
          git add content/posts/ static/images/
          if ! git diff --cached --quiet; then
            git commit -m "chore: sync content from S3"
            git push
          else
            echo "No changes to commit"
          fi

